### ISSUE TITLE
Could not find hmmsearch database /data/alphafold/db_20211214/pdb_seqres/pdb_seqres.txt

### ISSUE THREAD

**Issue by dre1gin** [uvarc/rivanna-docker#4]
I have been trying to run multimeric alphafold 2.1.2 version and I keep getting this message. The pdb_seqres and mmcif fold has been updated and I checked the path (it seems to be correct).
Does anyone know how to solve this issue?
The monomeric setting is running fine.
The full error log is below:
E0216 18:03:50.561251 47933169301760 hmmsearch.py:64] Could not find hmmsearch database /data/alphafold/db_20211214/pdb_seqres/pdb_seqres.txt
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 445, in <module>
    app.run(main)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 339, in main
    template_searcher = hmmsearch.Hmmsearch(
  File "/app/alphafold/alphafold/data/tools/hmmsearch.py", line 65, in __init__
    raise ValueError(f'Could not find hmmsearch database {database_path}')
ValueError: Could not find hmmsearch database /data/alphafold/db_20211214/pdb_seqres/pdb_seqres.txt

Thank you!

**Comment by rsdmse** [comment]
Assuming you're using Docker, I would suggest using `--entrypoint bash` to start up a shell and check whether `/data/alphafold/db_20211214/pdb_seqres` exists and whether it contains the txt file. If not, your bind-mount command may be incorrect. If yes, verify if your download was intact.

For further troubleshooting I'm afraid you'll have to open an issue with the DeepMind team.

**Comment by dre1gin** [comment]
I am using a singularity container to run it (build it using uvarc docker file for Alphafold 2.1.2)... 
the file exists in the path (I checked that several times).
The monomeric setting is running fine for me so I am not sure how my bind-mount command may not be correct for this specific case.
I use the following slurm file to run it:
#!/bin/bash
#SBATCH --job-name alphafold-run 
#SBATCH -p gpu 
#SBATCH -q wildfire 
#SBATCH --time=1-00:00:00 
#SBATCH --gres=gpu:2 
#SBATCH --cpus-per-task=8 
#SBATCH --mem=40G 
#SBATCH -o /home/%u/alphafold2/alphafold_output/slurm.%j.out 
#SBATCH -e /home/%u/alphafold2/alphafold_output/slurm.%j.err 
#set the environment PATH
export PYTHONNOUSERSITE=True
module purge
module load singularity/3.8.0 
export ALPHAFOLD_DATA_PATH=/data/alphafold/db_20210825
export USER_ALPHAFOLD_DIR=/home/akanygin/alphafold2
export FASTA_FILE=input.fasta
#BELOW 2 LINES ARE FOR JOBS RUNNING on multiple GPUs (below example is for 2) 
#export TF_FORCE_UNIFIED_MEMORY=1 
#export XLA_PYTHON_CLIENT_MEM_FRACTION=2.0
#export XLA_PYTHON_CLIENT_ALLOCATOR=platform
#Run the command
singularity run --nv \
-B $ALPHAFOLD_DATA_PATH:/data/alphafold/db_20211214 \
-B .:/etc \
--pwd  /app/alphafold $USER_ALPHAFOLD_DIR/alphafold.sif \
--data_dir=/data/alphafold/db_20211214 \
--fasta_paths=/etc/$FASTA_FILE  \
--output_dir=$USER_ALPHAFOLD_DIR/alphafold_output  \
--model_preset=multimer \
--db_preset=full_dbs \
--use_gpu_relax=True \
--pdb_seqres_database_path=/data/alphafold/db_20211214/pdb_seqres/pdb_seqres.txt \
--uniprot_database_path=/data/alphafold/db_20211214/uniprot/uniprot.fasta \
--bfd_database_path=/data/alphafold/db_20211214/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
--uniref90_database_path=/data/alphafold/db_20211214/uniref90/uniref90.fasta  \
--mgnify_database_path=/data/alphafold/db_20211214/mgnify/mgy_clusters.fa   \
--template_mmcif_dir=/data/alphafold/db_20211214/pdb_mmcif/mmcif_files  \
--obsolete_pdbs_path=/data/alphafold/db_20211214/pdb_mmcif/obsolete.dat \
--uniclust30_database_path=/data/alphafold/db_20211214/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
--max_template_date=

**Comment by rsdmse** [comment]
Since I am not an administrator on your cluster, it is hard for me to troubleshoot this for you. You can try to download the pdb_seqres dataset again. I suspect the download may not be intact.

Users on our cluster are not having this problem.

**Comment by dre1gin** [comment]
I contacted my admin and he redownloaded the pdbseq and mmcifs yesterday for me. It did not help to solve the issue.
Since I used uvarc docker image for the build I was hoping it is a known issue or I made an obvious error in my slurm script...
Anyway, thank you for your replies!

**Comment by rsdmse** [comment]
Your Singularity command looks fine to me. Check `/data/alphafold/db_20210825` on the host filesystem - are all the files in that directory? But I'm sure you've done this already.

As a final sanity check, resubmit the job but with
```
singularity exec -B $ALPHAFOLD_DATA_PATH:/data/alphafold/db_20211214 $USER_ALPHAFOLD_DIR/alphafold.sif wc /data/alphafold/db_20211214/pdb_seqres/pdb_seqres.txt
```
The result on our cluster is `1336732 4864919 218452419`.

I wish I could be of more help, but I'm afraid that's all I can think of.
